name: test

on:
  workflow_dispatch:
  push:
    tags:
    - '*'

jobs:
  release_policy:
    runs-on: ubuntu-latest
    name: build

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Read config
      id: config
      uses: gertd/yaml-reader-action@v1.0.2
      with:
        file: .github/config.yaml

    - name: Dump result
      id: "dump"
      run: |
        echo "GITHUB_OUT = ${GITHUB_OUTPUT}"
        echo "server = ${{ steps.config.outputs.server }}"
        echo "username = ${{ steps.config.outputs.username }}"
        echo "repo = ${{ steps.config.outputs.repo }}"

    - name: Read test2
      id: test2
      uses: gertd/yaml-reader-action@v1.0.2
      with:
        file: ./buf.gen.yaml
        json: true

    - name: Dump test2 results
      id: test2-dump
      run: |
        echo "name = ${{ fromJson(steps.test2.outputs.data).plugins[0].name }}"
